// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/info": {
            "get": {
                "description": "获取用户信息",
                "summary": "获取信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": {\"roles\": role, \"introduction\": xxx, \"avatar\": xxx, \"name\": username} }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "\"username\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "\"password\"",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": null }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": null }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/add": {
            "post": {
                "description": "添加单个用户",
                "consumes": [
                    "application/json"
                ],
                "summary": "添加单个用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "\"username\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "\"password\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role",
                        "name": "\"role\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "department",
                        "name": "\"department\"",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": null }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/delete": {
            "post": {
                "description": "删除单个用户",
                "consumes": [
                    "application/json"
                ],
                "summary": "删除单个用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "\"id\"",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": null }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/list": {
            "get": {
                "description": "获取所有用列表",
                "summary": "获取所有用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pageNum",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": {\"items\": listObj, \"total\": totalNum}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/user/update": {
            "post": {
                "description": "添加单个用户",
                "consumes": [
                    "application/json"
                ],
                "summary": "添加单个用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "\"id\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "username",
                        "name": "\"username\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "\"password\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "role",
                        "name": "\"role\"",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "department",
                        "name": "\"department\"",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"message\": \"ok\", \"data\": null }",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "127.0.0.1:20005",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "author-admin restful API",
	Description:      "This is the backend of author-admin system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
